FROM ubuntu:18.04
RUN apt-get update -qq \
    && apt-get install -y software-properties-common \
    && apt-get install -y python3-pip python3-dev \ 
    && cd /usr/local/bin \ 
    && apt-get update \ 
    && ln -s /usr/bin/python3 python \ 
    && pip3 install --upgrade pip \
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*# Add User with Non Root Access
RUN mkdir -p /home/food-vibe
COPY ./requirements.txt /home/food-vibe/requirements.txt
COPY . /home/food-vibe/
RUN pip3 install -r /home/food-vibe/requirements.txt
EXPOSE 8080
WORKDIR /home/food-vibe/
CMD ["python","index.py"]